[workspace]
resolver = "2"
members = [
    "belt-ctr",
    "cbc",
    "cts",
    "cfb8",
    #"cfb-mode",
    #"ctr",
    #"ige",
    #"ofb",
    #"pcbc"
]

[profile.dev]
opt-level = 2

[patch.crates-io]
aes        = { git = "https://github.com/RustCrypto/block-ciphers.git" }
belt-block = { git = "https://github.com/RustCrypto/block-ciphers.git" }
