[workspace]
resolver = "2"
members = [
    "belt-ctr",
    "cbc",
    "cfb8",
    "cfb-mode",
    "ctr",
    "ige",
    "ofb",
    "pcbc",
]

[patch.crates-io]
# please re-enable the minimal-versions when you remove those patches.
# https://github.com/RustCrypto/block-ciphers/pull/413
aes        = { git = "https://github.com/RustCrypto/block-ciphers.git" }
belt-block = { git = "https://github.com/RustCrypto/block-ciphers.git" }
kuznyechik = { git = "https://github.com/RustCrypto/block-ciphers.git" }
magma      = { git = "https://github.com/RustCrypto/block-ciphers.git" }
